DROP TABLE INVENTORY CASCADE CONSTRAINTS;
CREATE TABLE INVENTORY (
  ProductID INTEGER PRIMARY KEY,
  ProductDesc VARCHAR(30) NOT NULL,
  ProductPrice NUMERIC(8, 2) NOT NULL,
  ProductStockAmount INTEGER NOT NULL
);

DROP TABLE ORDERS CASCADE CONSTRAINTS;
CREATE TABLE ORDERS (
  OrderID INTEGER PRIMARY KEY,
  OrderType VARCHAR(10) NOT NULL,
  OrderCompleted INTEGER NOT NULL,
  OrderPlaced DATE NOT NULL,
  CONSTRAINT CheckOrderType CHECK (OrderType IN ('InStore', 'Collection', 'Delivery')),
  CONSTRAINT CheckOrderCompleted CHECK (OrderCompleted IN (0, 1))
);

DROP TABLE ORDER_PRODUCTS;
CREATE TABLE ORDER_PRODUCTS (
  OrderID INTEGER NOT NULL,
  ProductID INTEGER NOT NULL,
  ProductQuantity INTEGER NOT NULL,
  PRIMARY KEY (OrderID, ProductID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
  FOREIGN KEY (ProductID) REFERENCES INVENTORY(ProductID)
);

DROP TABLE DELIVERIES;
CREATE TABLE DELIVERIES (
  OrderID INTEGER PRIMARY KEY,
  FName VARCHAR(30) NOT NULL,
  LName VARCHAR(30) NOT NULL,
  House VARCHAR(30) NOT NULL,
  Street VARCHAR(60) NOT NULL,
  City VARCHAR(30) NOT NULL,
  DeliveryDate DATE NOT NULL,
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

DROP TABLE COLLECTIONS;
CREATE TABLE COLLECTIONS (
  OrderID INTEGER PRIMARY KEY,
  FName VARCHAR(30) NOT NULL,
  LName VARCHAR(30) NOT NULL,
  CollectionDate DATE NOT NULL,
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

DROP TABLE STAFF CASCADE CONSTRAINTS;
CREATE TABLE STAFF (
  StaffID INTEGER PRIMARY KEY,
  FName VARCHAR(30) NOT NULL,
  LName VARCHAR(30) NOT NULL
);

DROP TABLE STAFF_ORDERS;
CREATE TABLE STAFF_ORDERS (
  StaffID INTEGER,
  OrderID INTEGER,
  PRIMARY KEY (StaffID, OrderID),
  FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

DROP SEQUENCE order_seq;
CREATE SEQUENCE order_seq start with 1;

DROP SEQUENCE product_seq;
CREATE SEQUENCE product_seq start with 1;

DROP SEQUENCE staff_seq;
CREATE SEQUENCE staff_seq start with 1;

CREATE OR REPLACE FUNCTION find_OrderID (y INTEGER)
RETURN INTEGER
IS
  x INTEGER;
BEGIN
  SELECT OrderID
  INTO x
  FROM ORDERS
  WHERE OrderID = y;
  RETURN x;
EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION find_ProductID (y INTEGER)
RETURN INTEGER
IS
  x INTEGER;
BEGIN
  SELECT ProductID
  INTO x
  FROM INVENTORY
  WHERE ProductID = y;
  RETURN x;
EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION find_StaffID (y INTEGER)
RETURN INTEGER
IS
  x INTEGER;
BEGIN
  SELECT StaffID
  INTO x
  FROM STAFF
  WHERE StaffID = y;
  RETURN x;
EXCEPTION WHEN NO_DATA_FOUND THEN
  RETURN NULL;
END;
/

CREATE OR REPLACE TRIGGER order_autoinc
  BEFORE
  INSERT
  ON ORDERS
  FOR EACH ROW
DECLARE
  y INTEGER := order_seq.nextval;
  x INTEGER := find_OrderID(y);
BEGIN
  IF :new.OrderID IS NULL THEN
    WHILE (x IS NOT NULL)
    LOOP
      y := y + 100;
      x := find_OrderID(y);
    END LOOP;
    :new.OrderID := y;
  ELSIF :new.OrderID <= 0 THEN
    DBMS_OUTPUT.PUT_LINE('ORDERID MUST BE GREATER THAN 0');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER product_autoinc
  BEFORE
  INSERT
  ON INVENTORY
  FOR EACH ROW
DECLARE
  y INTEGER := product_seq.nextval;
  x INTEGER := find_ProductID(y);
BEGIN
  IF :new.ProductID IS NULL THEN
    WHILE (x IS NOT NULL)
    LOOP
      y := y + 100;
      x := find_ProductID(y);
    END LOOP;
    :new.ProductID := y;
  ELSIF :new.ProductID <= 0 THEN
    DBMS_OUTPUT.PUT_LINE('ORDERID MUST BE GREATER THAN 0');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER staff_autoinc
  BEFORE
  INSERT
  ON STAFF
  FOR EACH ROW
DECLARE
  y INTEGER := staff_seq.nextval;
  x INTEGER := find_StaffID(y);
BEGIN
  IF :new.StaffID IS NULL THEN
    WHILE (x IS NOT NULL)
    LOOP
      y := y + 100;
      x := find_StaffID(y);
    END LOOP;
    :new.StaffID := y;
  ELSIF :new.StaffID <= 0 THEN
    DBMS_OUTPUT.PUT_LINE('ORDERID MUST BE GREATER THAN 0');
  END IF;
END;
/

-- CREATE OR REPLACE TRIGGER date_check
--   BEFORE
--   INSERT
--   ON COLLECTIONS
--   FOR EACH ROW
-- END;
-- /
